pipeline:
  build_and_test:
    image: quay.io/ukhomeofficedigital/java8-mvn:v3.5.2.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_REPO=docker.digital.homeoffice.gov.uk
    commands:
      - mkdir -p /root/.docker
      - "MAVEN_OPTS=-Xmx512m mvn -B --quiet dependency:resolve"
      - export DEPLOY_HASH=$${DRONE_TAG:-$${DRONE_COMMIT:0:8}}
      - "MAVEN_OPTS=-Xmx512m mvn -B --quiet clean install -Dimage.tag=$${DEPLOY_HASH}"
    when:
      event:
        - push

  docker_build:
    image: docker:18.06.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_REPO=docker.digital.homeoffice.gov.uk
    commands:
      - docker build -t s3web:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  image_to_quay:
    image: docker:18.06.1-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag s3web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/s3web:$${DRONE_COMMIT_SHA}
      - docker tag s3web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/s3web:latest
      - docker push quay.io/ukhomeofficedigital/s3web:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/s3web:latest
    when:
      event: push
      branch: master

    tagged_image_to_quay:
      image: docker:18.06.1-ce
      secrets:
        - docker_password
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      commands:
        - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
        - docker tag s3web:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/s3web:$${DRONE_TAG}
        - docker push quay.io/ukhomeofficedigital/s3web:$${DRONE_TAG}
      when:
        event: tag