pipeline:
  build_and_test:
    image: quay.io/ukhomeofficedigital/java8-mvn:v3.5.2.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_REPO=docker.digital.homeoffice.gov.uk
    secrets:
      - artifactory_username
      - artifactory_password
    commands:
      - mkdir -p /root/.docker
      - 'echo "{ \"auths\": { \"$${DOCKER_REPO}\": { \"auth\": \"$(echo -n "$${ARTIFACTORY_USERNAME}:$${ARTIFACTORY_PASSWORD}" | base64 -w 0)\" } } }" > /root/.docker/config.json'
      - "MAVEN_OPTS=-Xmx512m mvn -B --quiet dependency:resolve"
      - export DEPLOY_HASH=$${DRONE_TAG:-$${DRONE_COMMIT:0:8}}
      - "MAVEN_OPTS=-Xmx512m mvn -B --quiet clean install -Dimage.tag=$${DEPLOY_HASH}"
    when:
      event:
        - push

  docker_build:
    image: docker:18.03.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_REPO=docker.digital.homeoffice.gov.uk
    commands:
      - docker build --rm -t "$${DOCKER_REPO}/${DRONE_REPO,,}:$${DRONE_COMMIT:0:8}" .
      - docker rmi "$${DOCKER_REPO}/${DRONE_REPO,,}:$${DRONE_COMMIT:0:8}"
    when:
      event:
        - push

  docker_push:
    image: docker:18.03.0-ce
      secrets:
        - artifactory_username
        - artifactory_password
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
        - DOCKER_REPO=docker.digital.homeoffice.gov.uk
      commands:
        - docker login -u="$${ARTIFACTORY_USERNAME}" -p="$${ARTIFACTORY_PASSWORD}" "$${DOCKER_REPO}"
        - docker build -t "$${DOCKER_REPO}/${DRONE_REPO,,}" .
        - docker tag "$${DOCKER_REPO}/${DRONE_REPO,,}" "$${DOCKER_REPO}/${DRONE_REPO,,}:$${DRONE_TAG}"
        - docker push "$${DOCKER_REPO}/${DRONE_REPO,,}"
      when:
        event: tag